version: '3.8'

services:
  web:
    build: .
    ports:
      - "8092:8092"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    # restart: always
    command: npm start
